license="${mod_license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
description='''Example mod description.'''
authors="com.ytgld.chest_item.test.ytgld"


[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[${neo_version},)" #mandatory
ordering="NONE"
side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
